#include<iostream>
using namespace std;
int main()
{
    /*
    int a;
    int b;

    cout<<"Enter the value of a:"<<endl;
    cin>>a;
    cout<<"Enter the value of b:"<<endl;
    cin>>b;
    cout<<"value of a and b is "<<a << b<<endl;
    
    
    
    
    if (a>b)
    {
        cout<<"A is greater"<<endl;
    }
    else{
        cout<<"B is greater"<<endl;
    }
    */
    
    int n;
    cout<<"Enter the value of n";
    cin>>n;
    

    if (n>0)
    {
        cout<<"N is positive "<<endl;
    }
    else if (n<0)
{
    cout<<"N is negative"<<endl;

}
else{
    cout<<"n is zero "<<endl;
}

   

}